service: sjofartstidningen-services

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

custom:
  defaultStage: development
  defaultRegion: eu-central-1

package:
  exclude:
    - '__mocks__/**'
    - '.cache/**'
    - 'misc/**'
    - 'services/**'
    - 'test/**'
    - 'utils/**'
    - '*'
    - '!package.json'
    - '!build/**'
    - '!static/**'
    - '**/*.map'

environment:
  NODE_ENV: ${opt:stage, self:custom.defaultStage}
  MAILCHIMP_DC: ${env:MAILCHIMP_DC}
  MAILCHIMP_API_KEY: ${env:MAILCHIMP_API_KEY}
  MAILCHIMP_LIST_ID: ${env:MAILCHIMP_LIST_ID}
  GOOGLE_CLIENT_EMAIL: ${env:GOOGLE_CLIENT_EMAIL}
  GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
  GOOGLE_VIEW_ID: ${env:GOOGLE_VIEW_ID}
  SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}

functions:
  analytics:
    description: 'A weekly digest of useful analytics from Google and Mailchimp'
    handler: build/analytics.send
    events:
      - schedule:
        name: weekly
        description: 'Every monday at 6 am (UTC)'
        rate: cron(0 6 * * MON *)
        enabled: true
