service: sjofartstidningen-services

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

custom:
  defaultStage: dev
  defaultRegion: eu-central-1

package:
  exclude:
    - '.cache/**'
    - 'misc/**'
    - 'services/**'
    - 'test/**'
    - 'utils/**'
    - '*'
    - '!package.json'
    - '!build/**'
    - '!static/**'
    - '**/*.map'

functions:
  analytics:
    description: 'A weekly digest of useful analytics from Google and Mailchimp'
    handler: build/analytics.send
    events:
      - schedule:
        name: weekly
        description: 'Every monday at 6 am (UTC)'
        rate: cron(0 6 * * MON *)
        enabled: true
