service: sjofartstidningen-services

plugins:
  - serverless-api-cloudfront

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  apiKeys:
    - name: render-email-${opt:stage}
      description: 'Key to access render-email endpoint'

custom: ${file(./serverless.config.js)}

package:
  exclude:
    - '**/*'
  include:
    - build/**

functions:
  analytics:
    description: 'A weekly digest of useful analytics from Google and Mailchimp'
    handler: build/analytics.send
    timeout: 10
    environment:
      VERSION: '1.0.3'
      NODE_ENV: ${opt:stage, self:custom.defaultStage}
      MAILCHIMP_DC: ${env:MAILCHIMP_DC}
      MAILCHIMP_API_KEY: ${env:MAILCHIMP_API_KEY}
      MAILCHIMP_LIST_ID: ${env:MAILCHIMP_LIST_ID}
      GOOGLE_CLIENT_EMAIL: ${env:GOOGLE_CLIENT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
      GOOGLE_VIEW_ID: ${env:GOOGLE_VIEW_ID}
      SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    events:
      - schedule:
          name: weekly-${self:provider.stage}
          description: 'Every monday at 6 am (UTC)'
          rate: cron(0 6 ? * MON *)
          enabled: true

  render-mail:
    description: 'Render provided mjml-string into html'
    handler: build/render-mail.render
    environment:
      VERSION: '1.0.0'
      NODE_ENV: ${opt:stage, self:custom.defaultStage}
    events:
      - http:
          path: render-mail
          method: post
          cors: true
          private: true
