service: sjofartstidningen-services
frameworkVersion: '2'

variablesResolutionMode: 20210326

plugins:
  - serverless-api-cloudfront

useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${sls:stage}
  region: eu-north-1
  lambdaHashingVersion: '20201221'
  apiGateway:
    apiKeys:
      - name: render-email-${sls:stage}
        description: 'Key to access render-email endpoint'

custom:
  apiCloudFront:
    domain: ${env:DOMAIN}
    certificate: ${env:AWS_CERTIFICATE_ARN}
    compress: true
    cookies: none
    headers:
      - x-api-key
    querystring: all

package:
  exclude:
    - '**/*'
  include:
    - build/**

functions:
  render-mail:
    description: 'Render provided mjml-string into html'
    handler: build/render-mail.render
    environment:
      VERSION: '1.0.1'
      NODE_ENV: ${sls:stage}
    events:
      - http:
          path: render-mail
          method: post
          cors: true
          private: true
