service: sjofartstidningen-services
frameworkVersion: '3'

useDotenv: true
plugins:
  - serverless-api-cloudfront

params:
  default:
    domain: ${sls:stage}.services.sjofartstidningen.se
  production:
    domain: services.sjofartstidningen.se

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${sls:stage}
  region: eu-north-1
  apiGateway:
    apiKeys:
      - name: render-email-${sls:stage}
        description: 'Key to access render-email endpoint'

custom:
  apiCloudFront:
    domain: ${param:domain}
    certificate: ${env:AWS_CERTIFICATE_ARN}
    compress: true
    cookies: none
    headers:
      - x-api-key
    querystring: all

package:
  exclude:
    - '**/*'
  include:
    - build/**

functions:
  render-mail:
    description: 'Render provided mjml-string into html'
    handler: build/render-mail.render
    environment:
      VERSION: '1.0.1'
      NODE_ENV: ${sls:stage}
      POWERTOOLS_SERVICE_NAME: render-mail
    events:
      - http:
          path: render-mail
          method: post
          cors: true
          private: true
