name: Production
on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: deploy staging
        run: npx serverless deploy function -f render-email
        env:
          STAGE: production
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_CERTIFICATE_ARN: ${{ secrets.AWS_CERTIFICATE_ARN }}
